export const helpPage = {
    users : 'menuUser',
    order : 'menuOrder',
    catalog : 'menuCatalog',
    locations : 'menuLocation',
    settings : 'menuSettings',
    statistics : 'menuStatistics',
    subscription : 'menuSubscription',
    customers: 'menuCustomers',
    billing: 'menuBilling',
    partner : 'menuPartner',
    register : 'menuRegisterStore',
    sharePreview: 'menuSharePreview',
    catalogOffer: 'menuCatalogOffer',
    catalogPriceVariants: 'menuCatalogPriceVariants',
    catalogOptionGroup: 'menuCatalogOptionGroup',
    catalogCategory: 'menuCatalogCategory',
    catalogManageByExcel: 'menuManageByExcel',
    catalogChangeAndTranslateLable: 'menucatalogChangeAndTranslateLable',
    catalogImportFromPhoto: 'menucatalogImportFromPhoto',
    settingsStoreDetails : 'menuSettingsStoreDetails',
    settingsAddZones : 'menuSettingsAddZones',
    settingsStoreOrdering : 'menuSettingsStoreOrdering',
    settingsStorePayment : 'menuSettingsStorePayment',
    settingsStorePickup : 'menuSettingsStorePickup',
    settingsStoreDelivery : 'menuSettingsStoreDelivery',
    SettingsStoreLocations : 'menuSettingsStoreLocations',
    settingsStoreCatalog : 'menuSettingsStoreCatalog',
    settingsStoreOrderingRule : 'menuSettingsStoreOrderingRule',
    SettingsStoreSchedules : 'menuSettingsStoreSchedules',
    SettingsStoreDiscountVouchers : 'menuSettingsStoreDiscountVouchers',
    SettingsStoreMarketing : 'menuSettingsStoreMarketing',
    SettingsStoreDomainsAndApps : 'menuSettingsStoreDomainsAndApps',
    SettingsStoreIntegrations : 'menuSettingsStoreIntegrations',
  };
